### ISSUE TITLE
Compile guide and version statement

### ISSUE THREAD

**Issue by rreinecke** [Akash-Nag/MDL-Suite#3]
Please add a description with which versions of java your build is compatible with and consider adding a small build instruction.

With the default Ubuntu JRE I'm getting:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: mdlg/MDLG has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

**Comment by rreinecke** [comment]
And please add a description of dependencies if there are any.

**Comment by akashnag** [comment]
Thank you for your suggestions. I have now included the relevant JVM information in the README.

**Comment by akashnag** [comment]
The JARs have been compiled using Oracle Java 10.0.2, running on Ubuntu 18.10

**Comment by rreinecke** [comment]
Thanks! Please add how to build the jar as well (just as convenience) because `java mdlg.MDLG` is producing: `java mdlg.MDLG                    
Maze Description Language Generator - v1.0
by Akash Nag. This software is open-source and is distributed under Artistic License 2.0.
Usage:
	 java -jar mdlg.jar <config-file> <output-files-in-mdl-format>
`

**Comment by rreinecke** [comment]
Furthermore: `java mdlg.MDLG example/maze.config maze1 maze2 maze3` is yielding `java.io.FileNotFoundException: example/maze.config (No such file or directory)`

**Comment by akashnag** [comment]
Sorry, it should be examples/maze.config instead of example/maze.config

**Comment by akashnag** [comment]
The instructions for building the JARs are now available in the README. I have also added the documentation.
