### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by rreinecke** [Akash-Nag/MDL-Suite#5]
As also mentioned in  #4 consider adding test cases. This allows me to further evaluate the functionality of the code and other to contribute to the project and overall maintain the quality of the software.

**Comment by akashnag** [comment]
An automated test utility has been added as a shell script inside the tests directory

**Comment by rreinecke** [comment]
Please make yourself familiar with JUnit and add according automated tests to your code that allow us and future developers to verify the functionality of your code. The shell script is not sufficient.

**Comment by rreinecke** [comment]
> Firsly, there can be a formal proof of the correctness of the algorithm in the paper itself, but I think the format of JOSS papers will not be able to accomodate that. Secondly, I can include a function which, given a generated maze matrix, will print out any one path (as a list of coordinates) from the entrance to the exit, or alternately, a test which will return true/false depending on whether or not a path exists. 

You are right a proof is not necessary and I suppose there is already a paper on that? did you cite it? Maybe you could add the reference in the docstring as well

Concerning the the test: Reading your suggestion I'm guessing that you never wrote uni tests before. Which is ok but you should familiarize yourself with the concept (see also comment above).
Looking at  https://github.com/Akash-Nag/MDL-Suite/blob/master/mdlg/RandomMazeGenerator.java#L63 there is a lot of potential there for tests and also much more error handling. Possible test cases that come to my mind (you should think of more yourself and how to verify them):

*  What happens if all parameters are zero?
*  Are there edge cases were the method is not working as intended? e.g. see above think about raising an exception instead of just returning. You should test for correct error handling afterwards
* what about a very thin maze? Is it possible to basically have 1 million columns and 2 rows? Is it still generating something useful? You should test this.
*  Additionally to edge cases it would be helpful to just randomly generate a thousand mazes and test if there is a possible path through

All implemented in JUnit tests. That would greatly help to verify that your code is actually doing what you promise and help future development!

**Comment by akashnag** [comment]
Thank you so much for your inputs... I will read up on how to write these
tests and include them in the project in the coming weeks. I will get back
to you after I have made the necessary changes.

**Comment by rreinecke** [comment]
Any updates on this? Would be great to finish this review soon. Otherwise you should think about resubmitting.

**Comment by akashnag** [comment]
I'm extremely sorry for the delay (as I have too many engagements
right now). Yes, I think it would be better if I resubmit. Could you
guide me on the process? I mean, should I just withdraw the paper now,
and then submit it again as a new/fresh submission later?

On 25/11/2019, Robert Reinecke <notifications@github.com> wrote:
> Any updates on this? Would be great to finish this review soon. Otherwise
> you should think about resubmitting.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Akash-Nag/MDL-Suite/issues/5#issuecomment-558232283


-- 
Akash Nag
Department of Computer Science
M.U.C. Women's College,
Burdwan 713104, West Bengal, India
Mobile: (+91) 98322-58023
E-mail: nag.akash.cs@gmail.com

**Comment by rreinecke** [comment]
I would think so. Ask the handling editor in the review thread directly.

**Comment by rreinecke** [comment]
Addressed in 05c8ee1
