### ISSUE TITLE
Running examples fails

### ISSUE THREAD

**Issue by rreinecke** [Akash-Nag/MDL-Suite#6]
1.  Please add the correct path to the maze.config in the README
2.  `java -jar mdlg.jar examples/maze.config maze1 maze2 maze3
1/3: maze generated successfully
2/3: maze generated successfully
3/3: maze generated successfully
` works, but `java -jar mdlc.jar maze1 
An error occurred during maze generation:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at mdlc.MDLC.main(MDLC.java:22)
` also the files generated in the first step are not called maze1.maze as in the README example.

**Comment by akashnag** [comment]
The following changes have been made:
1. The exact command to execute the tools from the root directory have been included in the README
2. I have added an automated test utility available as a shell-script inside the tests directory

**Comment by akashnag** [comment]
The tests generate the maze according to the configuration specified in the maze.config file. You can change these settings to obtain different results. e.g. The generated mazes are black-and-white by default. You can generate blue mazes (say) by adding the following setting at the end of maze.config:

[wall-color:rgb(0:0:255)]

After this change, re-executing the test will cause the wall colors to be blue.
